resolver: lts-18.28

flags: {}

extra-deps:
  - git: git@github.com:DaisukeBekki/JSeM.git
    commit: b725e62dd66cbbb4fe891ee84108d7a398f5dd71
  - git: git@github.com:DaisukeBekki/hasktorch-tools.git
    commit: 936928cdee27e179a5e3775d146046b107b0eba1
  - git: git@github.com:miyagawananako/lightblue.git
    commit: 89325dbadbdb9eda1889532b045861b8636e0d5a
  # - /Users/daidohinari/blab/mycode/lightblue

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true
